### ISSUE TITLE
Invalid OBJ content doesn't seem to throw an error

### ISSUE THREAD

**Issue by Yugloocamai** [sheenobu/go-obj#1] opened 2017-05-17 01:03 UTC
This code should throw an error:

r := NewReader(bytes.NewBuffer([]byte("FASDF!21!@#!@#12#")))

_, err := r.Read()
if err != nil {
	t.Errorf("Expected success, got err: '%s'", err)
	return
}

But no error is received.

**Comment by sheenobu** [comment] 2017-05-17 02:09
The new routing code here https://github.com/sheenobu/go-obj/commit/dbcf32e3bab7eea2bb9061c16c27c0245e038240 made unknown identifiers (the beginning F) skipped instead of a reported as errors. It's a bug, thank you.

**Comment by sheenobu** [comment] 2017-05-17 02:19
Removed my previous comment. Actually the reader should be able to support arbitrary types. There is a lot we just silently ignore right now, like `mtlib` and `s`. This is by design.

**Comment by sheenobu** [comment] 2017-05-17 22:09
This should be good to go. The `StandardSet` of non-failable entries are here: https://github.com/sheenobu/go-obj/blob/master/obj/standard.go

And `NewStandardReader` can be used to build a reader with these elements. Not all are supported but they will be silently ignored while your example should now fail.

**Comment by sheenobu** [comment] 2017-07-14 18:33
Fixed via #3

**Closed as completed by sheenobu** 2017-07-14 18:33 UTC
Labels: bug
